fix(eventviewer): fixed eventviewer updating client side state in a weird way
fix #3

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -25,15 +25,14 @@ if [ "$branch" = "master" ]; then
 	# 	exit 1
 	# fi
 
-fi
-
-# Lint code
-if lerna run lint; then
-	# Code is lint free
-	:
-else
-	echo "Code fails lint check"
-	exit 1
+	# Lint code
+	if lerna run lint; then
+		# Code is lint free
+		:
+	else
+		echo "Code fails lint check"
+		exit 1
+	fi
 fi
 
 # Apply prettier rules
